CREATE TABLE IF NOT EXISTS coinbase_price_10m (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  symbol TEXT NOT NULL DEFAULT 'BTC-USD',
  open_price_usd NUMERIC,
  high_price_usd NUMERIC,
  low_price_usd NUMERIC,
  close_price_usd NUMERIC,
  volume_btc NUMERIC,
  volume_usd NUMERIC,
  trade_count BIGINT,
  raw_payload JSONB,
  source_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS kraken_price_10m (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  symbol TEXT NOT NULL DEFAULT 'XBT/USD',
  open_price_usd NUMERIC,
  high_price_usd NUMERIC,
  low_price_usd NUMERIC,
  close_price_usd NUMERIC,
  volume_btc NUMERIC,
  volume_usd NUMERIC,
  trade_count BIGINT,
  raw_payload JSONB,
  source_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bitfinex_price_10m (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  symbol TEXT NOT NULL DEFAULT 'tBTCUSD',
  open_price_usd NUMERIC,
  high_price_usd NUMERIC,
  low_price_usd NUMERIC,
  close_price_usd NUMERIC,
  volume_btc NUMERIC,
  volume_usd NUMERIC,
  trade_count BIGINT,
  raw_payload JSONB,
  source_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gemini_price_10m (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  symbol TEXT NOT NULL DEFAULT 'BTCUSD',
  open_price_usd NUMERIC,
  high_price_usd NUMERIC,
  low_price_usd NUMERIC,
  close_price_usd NUMERIC,
  volume_btc NUMERIC,
  volume_usd NUMERIC,
  trade_count BIGINT,
  raw_payload JSONB,
  source_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mq_btc_price_fair_10m_details (
  bucket_start_utc TIMESTAMPTZ PRIMARY KEY,
  bitstamp_open_price NUMERIC,
  bitstamp_high_price NUMERIC,
  bitstamp_low_price NUMERIC,
  bitstamp_close_price NUMERIC,
  bitstamp_volume_btc NUMERIC,
  coinbase_open_price NUMERIC,
  coinbase_high_price NUMERIC,
  coinbase_low_price NUMERIC,
  coinbase_close_price NUMERIC,
  coinbase_volume_btc NUMERIC,
  binance_open_price NUMERIC,
  binance_high_price NUMERIC,
  binance_low_price NUMERIC,
  binance_close_price NUMERIC,
  binance_volume_btc NUMERIC,
  bybit_open_price NUMERIC,
  bybit_high_price NUMERIC,
  bybit_low_price NUMERIC,
  bybit_close_price NUMERIC,
  bybit_volume_btc NUMERIC,
  okx_open_price NUMERIC,
  okx_high_price NUMERIC,
  okx_low_price NUMERIC,
  okx_close_price NUMERIC,
  okx_volume_btc NUMERIC,
  kraken_open_price NUMERIC,
  kraken_high_price NUMERIC,
  kraken_low_price NUMERIC,
  kraken_close_price NUMERIC,
  kraken_volume_btc NUMERIC,
  bitfinex_open_price NUMERIC,
  bitfinex_high_price NUMERIC,
  bitfinex_low_price NUMERIC,
  bitfinex_close_price NUMERIC,
  bitfinex_volume_btc NUMERIC,
  gemini_open_price NUMERIC,
  gemini_high_price NUMERIC,
  gemini_low_price NUMERIC,
  gemini_close_price NUMERIC,
  gemini_volume_btc NUMERIC,
  fair_open_price NUMERIC,
  fair_high_price NUMERIC,
  fair_low_price NUMERIC,
  fair_close_price NUMERIC,
  total_volume_btc NUMERIC,
  source_count INTEGER NOT NULL DEFAULT 0,
  source_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  composition_method TEXT NOT NULL DEFAULT 'volume_weighted_ohlc_v1',
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mq_btc_price_fair_10m_details_updated_at
ON mq_btc_price_fair_10m_details(updated_at DESC);
